created models,connection,routes
the-10x-academy/apprenticeship-team-f pull request #2
Opened 2021-01-28 11:56 UTC by vamsi2711

2021-01-29 09:01 UTC, ajuk95 reviewed
reviewed

2021-02-05 13:46 UTC, rahulbudhrani01 approved these changes

2021-02-05 13:46 UTC, rahulbudhrani01 requested changes
Remove mongoose changes from app.js and move it to a new file

2021-02-05 15:18 UTC, rahulbudhrani01 approved these changes

2021-02-05 15:18 UTC, merged